<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 */
?>
<!--<img class="footer-logo" src="/images/tpuk-logo-footer.svg" alt="Thomas Performance logo">-->
<img
    class="footer-logo"
    src="<?= $block->getViewFileUrl('Tpuk_Theme::images/tpuk-logo-footer.svg') ?>"
    alt="Thomas Performance logo"
>
<div class="social social-white">
    <a href="https://www.facebook.com/thomasperformanceuk" target="_blank" rel="noopener">
        <div class="social-block facebook">&nbsp;</div>
    </a>
    <a href="https://twitter.com/TPerformanceUK" target="_blank" rel="noopener">
        <div class="social-block twitter">&nbsp;</div>
    </a>
    <a href="https://www.youtube.com/channel/UC6IicWTd4_uQRRLlAFuJz1A/feed" target="_blank" rel="noopener">
        <div class="social-block youtube">&nbsp;</div>
    </a>
    <a href="https://www.instagram.com/thomasperformance" target="_blank" rel="noopener">
        <div class="social-block instagram">&nbsp;</div>
    </a>
</div>
